# Use container-based infrastructure for quicker build start-up
sudo: false
language: minimal
env:
  # Path to 'hadolint' binary
  HADOLINT: "${HOME}/hadolint"
install:
  # Download hadolint binary and set it as executable
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-$(uname -s)-$(uname -m)"
  - chmod 700 ${HADOLINT}
  - apt-get update
  - apt-get install lynis -y
script:
  - lynis audit dockerfile Dockerfile
  - ${HADOLINT} --ignore DL3003 --ignore DL3008 Dockerfile
  - docker build . -t varnav/binance-node
  - docker run --rm -d --name binance-testnet -e "BNET=testnet" varnav/binance-node
  - docker run --rm -d --name binance -e "BNET=prod" varnav/binance-node
  - sleep 5
  - docker logs binance-testnet | head -n 20
  - docker logs binance | head -n 20
  - sleep 15
  - docker logs --tail 20 binance-testnet
  - docker logs --tail 20 binance
  - docker exec -t binance-testnet tbnbcli version
  - docker exec -t binance bnbcli version
  - docker stop binance-testnet
  - docker stop binance
