apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-node
  labels:
    app: binance-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-node
  template:
    metadata:
      labels:
        app: binance-node
    spec:
      containers:
      - name: binance-node
        image: varnav/binance-node
        ports:
        - name: binance-rpc
          containerPort: 27147
        - name: binance-public
          containerPort: 27146
        resources:
          limits:
            memory: "4Gi"
            cpu: 2
        volumeMounts:
          - name: binance-data
            mountPath: /opt/bnbchaind
      initContainers:
      - name: init-ulimitn
        image: busybox
        command: ["sh", "-c", "ulimit -n 16000"]
        securityContext:
          privileged: true
      volumes:
      - name: binance-data